server:
  address: 127.0.0.1   # 只监听本机，如果要外网访问可以写 0.0.0.0
  port: 8081
spring:
  application:
    name: PaiResume
  # datasource config
  datasource:
    url: jdbc:mysql://localhost:3306/pairesume?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456 # change to your database password
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa config
  jpa:
    open-in-view: false # 推荐设置为 false，以关闭 OSIV 模式，避免潜在的性能问题
    hibernate:
      ddl-auto: update # 开发环境使用 update，生产环境建议使用 none 或 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  # redis config
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: # change to your redis password if any
      database: 0
  # mail config
  mail:
    host: smtp.qq.com # todo: change to your mail server
    port: 587
    username: your_email@example.com # todo: change to your email username
    password: your_email_password # todo: QQ邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# custom config
app:
  jwt:
    secret: "jK3r9m8sT2pQvX4zW1bC0uV7nL6fR5eH8yZ9aBqM3tF4gS0u666"
    access-token-expiration-ms: 1800000 # 30 minutes
    refresh-token-expiration-ms: 604800000 # 7 days

# Alipay Configuration
alipay:
  app-id: 填写你的APP ID
  private-key: 填写你的应用私钥
  alipay-public-key: 填写你的支付宝公钥
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do # 沙箱环境，生产环境需要修改
  domain: http://localhost:8080 # 用于拼接回调地址
  sign-type: RSA2
  format: json
  charset: utf-8

# AI Optimize Configuration
ai:
  deepseek:
    provider: api
    prompt: |
      你是一位顶级的技术招聘官和简历优化专家，尤其擅长指导计算机领域的应届生和实习生。你的任务是优化下方提供的简历模块 JSON 内容，使其在求职（开发、测试、运维岗位）时更具竞争力。

      **核心优化原则:**
      *   **使用STAR法则**: 确保描述清晰地反映出项目/实习的背景（Situation）、你的任务（Task）、你采取的具体行动（Action）以及最终达成的可量化成果（Result）。
      *   **强化技术动词**: 使用如“实现”、“开发”、“重构”、“部署”、“自动化”、“优化”等具体的、有力的技术动词，避免使用“负责”、“参与”等模糊词汇。
      *   **量化成果**: 尽可能将工作成果量化，例如：“将接口响应时间从500ms优化至100ms”、“通过自动化脚本将部署时间缩短了10分钟”、“将测试覆盖率从70%提升至90%”。
      *   **突出技术栈**: 在描述中自然地融入项目或经历中使用的关键技术、工具或框架。

      **重要规则:**
      1.  你必须保持与输入完全相同的 JSON 结构。不要添加、删除或重命名任何键。输出结果必须是能被直接解析的、格式正确的 JSON。
      2.  你的回答必须且仅包含优化后的纯净 JSON 内容。不要包含任何额外的文字、解释、问候，也不要使用 ```json ... ``` 这种 Markdown 格式。

      待优化的 JSON 内容如下:
      ---
      {INPUT_JSON_HERE}
      ---
    api:
      url: https://api.deepseek.com/v1
      key: sk-your-deepseek-api-key 
      model: deepseek-chat
    local:
      url: # 本地部署url
      model:  # 本地部署的模型名
